name: Build PDF Manual from Markdown

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/build_pdf.yml'
  workflow_dispatch: # manual trigger

jobs:
  build_pdf:
    runs-on: ubuntu-latest # use static version?

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Get current date and run number for versioning
        id: version_info
        run: |
          echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV # used to get unique output everytime a manual is generated
          echo "Generated version suffix: ${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}"

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended

      - name: Get list of Markdown files in desired order
        id: markdown_files_list
        run: |
          FILE_LIST=$(find docs -name "*.md" | sort | tr '\n' ' ') # convert newlines to spaces so pandoc can read them as args
          echo "Found Markdown files for PDF compilation: $FILE_LIST"
          echo "file_list=$FILE_LIST" >> $GITHUB_OUTPUT

      - name: Compile PDF with Pandoc
        run: |
          OUTPUT_FILENAME="versions/manual-${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}.pdf"
          echo "Compiling PDF as: $OUTPUT_FILENAME"
        
          pandoc \
            --from markdown \
            --to pdf \
            --output "$OUTPUT_FILENAME" \
            --table-of-contents \
            --toc-depth=3 \
            --number-sections \
            # --resource-path=./images/tex_resources \
            # --template=./templates/pdf_template.tex \ # these two parameters can be included to make the document from a template but requires some finetuning to work well
            ${{ steps.markdown_files_list.outputs.file_list }} # the markdown documents found in previous step

      - name: Configure Git User (Bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Commit and Push PDF to Repository
        run: |
          PDF_FILE="versions/manual-${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}.pdf"
          git add "$PDF_FILE"
          if git diff --cached --exit-code; then # check for changes
            echo "No new PDF changes to commit."
          else
            git commit -m "feat(manual): Add manual ${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }} [skip ci]" # IMPORTANT!! do not remove skip ci or it will loop forever
            git push origin ${{ github.ref_name }} # this could be a different branch to avoid errors
            echo "Successfully pushed $PDF_FILE to the repository."
          fi
