name: Convert DOCX to PDF

on:
  push:
    paths:
      - 'docx/**'

jobs:
  convert-docx-to-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pandoc and TeX Live packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-xetex

      - name: Get changed or added DOCX files
        id: changed-files
        run: |
          CHANGED_DOCX_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep 'docx/.*\.docx$' | tr '\n' ' ')
          echo "changed_docx_files=${CHANGED_DOCX_FILES}" >> $GITHUB_OUTPUT
          echo "Found the following changed/added DOCX files:"
          echo "${CHANGED_DOCX_FILES}"

      - name: Convert DOCX to PDF
        if: ${{ steps.changed-files.outputs.changed_docx_files != '' }}
        run: |
          OUTPUT_DIR="${{ vars.ARTIFACT_DIR || 'artifacts' }}"
          mkdir -p "$OUTPUT_DIR"

          for docx_file in ${{ steps.changed-files.outputs.changed_docx_files }}; do
            if [ -f "$docx_file" ]; then
              base_name=$(basename "$docx_file" .docx)
              current_timestamp=$(date +%Y%m%d)
              final_base_name="${base_name}_${current_timestamp}"
              output_pdf="$OUTPUT_DIR/${final_base_name}.pdf"
              pandoc "$docx_file" -o "$output_pdf" --pdf-engine=xelatex
            fi
          done

      - name: Commit and push generated PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Auto-generated PDFs from DOCX changes"
          branch: ${{ github.ref_name }}
          file_pattern: "${{ vars.ARTIFACT_DIR || 'artifacts' }}/*.pdf"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
