name: Build PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/build_pdf.yml'
  workflow_dispatch: # manual trigger
  workflow_call:
    inputs:
      file_base_name:
        required: false
        type: string
        default: 'my-document'

      output_dir:
        required: true
        type: string
        default: 'artifacts'

      docs_dir:
        required: true
        type: string
        default: 'docs'

      images_dir:
        required: true
        type: string
        default: 'images'

      template_path:
        required: false
        description: '"remote_template" will download and use the remote_template'
        type: string
        default: 'remote_template'

    outputs:
      pdf_path:
        description: 'The full path to the generated PDF document'
        value: ${{ jobs.build_pdf.outputs.final_pdf_path }}

      artifact_url:
        description: 'URL to the workflow run artifacts'
        value: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      artifact_name:
        description: 'The exact name of the uploaded PDF artifact'
        value: ${{ jobs.build_pdf.outputs.uploaded_artifact_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      FILE_BASE_NAME: ${{ inputs.file_base_name || 'document' }} # change "my-base-document" to your liking! TODO: Add repo variable
      ARTIFACT_DIR: ${{ inputs.output_dir || vars.ARTIFACT_DIR || 'artifacts' }}
      DOCS_DIR: ${{ inputs.docs_dir || vars.DOCS_DIR || 'docs' }}
      IMAGES_DIR: ${{ inputs.images_dir || vars.IMAGES_DIR || 'images' }}
      DEFAULT_TEMPLATE: './templates/template.tex'

    outputs:
      final_pdf_path: ${{ steps.pandoc_compile.outputs.FINAL_PDF_CALL_PATH }}
      uploaded_artifact_name: ${{ env.VERSIONED_PDF_FILENAME_OUT }}

    steps:
      - name: Debug - Print Event Name in Reusable Workflow
        run: |
          echo "--- Reusable Workflow Event Debug ---"
          echo "The event name that triggered THIS reusable workflow is: ${{ github.event_name }}"
          echo "Is ${{ github.event_name }} equal to 'workflow_call'? ${{ github.event_name == 'workflow_call' }}"
          echo "--- End Debug ---"
    
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Set dynamic environment variables
        id: version_info
        run: |
          echo "VERSIONS_DIR=${{ env.ARTIFACT_DIR }}/versions" >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV # used to get unique output everytime a document is generated
          echo "Generated version suffix: ${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}"
          echo "TEMPLATE_PATH=${{ inputs.template_path || env.DEFAULT_TEMPLATE }}" >> $GITHUB_ENV # check if a template was given, otherwise use default

      - name: Set (& Download) Template Path
        run: |
          if [[ "${{ env.TEMPLATE_PATH }}" == "remote_template" ]]; then 
            echo "No template was given - downloading default"
            TEMPLATE_RAW_URL="https://raw.githubusercontent.com/yaouDev/automated-document-constructor/main/templates/template.tex"
            LOCAL_TEMPLATE_PATH="${{ runner.temp }}/template.tex"

            echo "Attempting to download template from: $TEMPLATE_RAW_URL"
            echo "Saving template to: $LOCAL_TEMPLATE_PATH"

            curl -L "$TEMPLATE_RAW_URL" -o "$LOCAL_TEMPLATE_PATH"

            if [ $? -eq 0 ] && [ -f "$LOCAL_TEMPLATE_PATH" ]; then
              echo "SUCCESS: Template downloaded and is ready at $LOCAL_TEMPLATE_PATH"
              head -n 5 "$LOCAL_TEMPLATE_PATH"
              echo "TEMPLATE_PATH=$LOCAL_TEMPLATE_PATH" >> $GITHUB_ENV
            else
              echo "ERROR: Failed to download template. Please double-check the TEMPLATE_RAW_URL."
              exit 1
            fi
          fi

          if [ ! -f "${{ env.TEMPLATE_PATH}}" ]; then
                # verify that the template is found
                echo "ERROR: Local template file NOT found at $TEMPLATE_PATH for ${{ github.event_name }} event!"
                exit 1
            fi

      - name: Create artifacts directories
        run: |
          mkdir -p ${{ env.VERSIONS_DIR }}
          echo "Ensured directory ${{ env.VERSIONS_DIR }} exists."

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended

      - name: Get list of Markdown files in desired order
        id: markdown_files_list
        run: |
          FILE_LIST=$(find ${{ env.DOCS_DIR }} -name "*.md" | sort | tr '\n' ' ') # convert newlines to spaces so pandoc can read them as args
          echo "Found Markdown files for PDF compilation: $FILE_LIST"
          echo "file_list=$FILE_LIST" >> $GITHUB_OUTPUT

      - name: Compile PDF with Pandoc
        id: pandoc_compile
        run: |
          VERSIONED_PDF_FILENAME="${{ env.FILE_BASE_NAME }}-${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}.pdf"
          VERSIONED_PDF_FULL_PATH="${{ env.VERSIONS_DIR }}/${VERSIONED_PDF_FILENAME}"
          LATEST_PDF_FULL_PATH="${{ env.ARTIFACT_DIR }}/${{ env.FILE_BASE_NAME }}.pdf"

          echo "VERSIONED_PDF_FULL_PATH_OUT=$VERSIONED_PDF_FULL_PATH" >> $GITHUB_ENV
          echo "LATEST_PDF_FULL_PATH_OUT=$LATEST_PDF_FULL_PATH" >> $GITHUB_ENV
          echo "VERSIONED_PDF_FILENAME_OUT=$VERSIONED_PDF_FILENAME" >> $GITHUB_ENV

          echo "FINAL_PDF_CALL_PATH=$VERSIONED_PDF_FULL_PATH" >> $GITHUB_OUTPUT

          echo "Compiling PDF as: $VERSIONED_PDF_FULL_PATH"
        
          pandoc \
            --from markdown \
            --to pdf \
            --output "$VERSIONED_PDF_FULL_PATH" \
            --table-of-contents \
            --toc-depth=3 \
            --number-sections \
            --template="${{ env.TEMPLATE_PATH }}" \
            --variable=date:"${{ env.CURRENT_DATE }}" \
            --resource-path="./:${{ env.IMAGES_DIR }}" \
            ${{ steps.markdown_files_list.outputs.file_list }} # the markdown documents found in previous step

          cp "$VERSIONED_PDF_FULL_PATH" "$LATEST_PDF_FULL_PATH"
          echo "Copied PDF to $LATEST_PDF_FULL_PATH"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSIONED_PDF_FILENAME_OUT }}
          path: ${{ env.VERSIONED_PDF_FULL_PATH_OUT }}
          retention-days: 1 # change if you want this to be the primary way to get your artifacts

      # Exclude blocks below this line if you do not wish the bot to push the PDFs to the repository -------------------------------------------------------

      - name: Configure Git User (Bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Commit and Push PDF to Repository
        run: |
          git add "${{ env.VERSIONED_PDF_FULL_PATH_OUT }}"
          git add "${{ env.LATEST_PDF_FULL_PATH_OUT }}"
          
          if git diff --cached --exit-code; then # check for changes
            echo "No new PDF changes to commit."
          else
            git commit -m "feat(manual): Add manual ${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }} [skip ci]" # IMPORTANT!! do not remove skip ci or it will loop forever
            git push origin ${{ github.ref_name }} # this could be a different branch to avoid errors
            echo "Successfully pushed $PDF_FILE to the repository."
          fi
