name: Build PDF

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/build_pdf.yml'
  workflow_dispatch: # manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_pdf:
    runs-on: ubuntu-latest # use static version?

    permissions:
      contents: write

    env:
      FILE_BASE_NAME: manual # change this to rename your output file!
      LATEST_ARTIFACT_DIR: artifacts
      VERSIONS_DIR: ${{ env.LATEST_ARTIFACT_DIR }}/versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Get current date and run number for versioning
        id: version_info
        run: |
          echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
          echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV # used to get unique output everytime a manual is generated
          echo "Generated version suffix: ${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}"

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-extra texlive-fonts-recommended

      - name: Get list of Markdown files in desired order
        id: markdown_files_list
        run: |
          FILE_LIST=$(find docs -name "*.md" | sort | tr '\n' ' ') # convert newlines to spaces so pandoc can read them as args
          echo "Found Markdown files for PDF compilation: $FILE_LIST"
          echo "file_list=$FILE_LIST" >> $GITHUB_OUTPUT

      - name: Compile PDF with Pandoc
        run: |
          VERSIONED_PDF_FILENAME="${{ env.FILE_BASE_NAME }}-${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }}.pdf"
          VERSIONED_PDF_FULL_PATH="${{ env.VERSIONS_DIR }}/${{ env.VERSIONED_PDF_FILENAME }}"
          LATEST_PDF_FULL_PATH="${{ env.LATEST_ARTIFACT_DIR }}/${{ env.FILE_BASE_NAME }}.pdf"

          echo "VERSIONED_PDF_FULL_PATH_OUT=$VERSIONED_PDF_FULL_PATH" >> $GITHUB_ENV
          echo "LATEST_PDF_FULL_PATH_OUT=$LATEST_PDF_FULL_PATH" >> $GITHUB_ENV
          echo "VERSIONED_PDF_FILENAME_OUT=$VERSIONED_PDF_FILENAME" >> $GITHUB_ENV

          echo "Compiling PDF as: $VERSIONED_PDF_FULL_PATH"
        
          pandoc \
            --from markdown \
            --to pdf \
            --output "$VERSIONED_PDF_FULL_PATH" \
            --table-of-contents \
            --toc-depth=3 \
            --number-sections \
            --template=./templates/template.tex \
            --variable=date:"${{ env.CURRENT_DATE }}" \
            ${{ steps.markdown_files_list.outputs.file_list }} # the markdown documents found in previous step

          cp "$VERSIONED_PDF_FULL_PATH" "$LATEST_PDF_FULL_PATH"
          echo "Copied PDF to $LATEST_PDF_FULL_PATH"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VERSIONED_PDF_FILENAME_OUT }}
          path: ${{ env.VERSIONED_PDF_FULL_PATH_OUT }}
          retention-days: 1 # change if you want this to be the primary way to get your artifacts

      - name: Configure Git User (Bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"

      - name: Commit and Push PDF to Repository
        run: |
          git add "${{ env.VERSIONED_PDF_FULL_PATH_OUT }}"
          git add "${{ env.LATEST_PDF_FULL_PATH_OUT }}"
          
          if git diff --cached --exit-code; then # check for changes
            echo "No new PDF changes to commit."
          else
            git commit -m "feat(manual): Add manual ${{ env.CURRENT_DATE }}-${{ env.RUN_NUMBER }} [skip ci]" # IMPORTANT!! do not remove skip ci or it will loop forever
            git push origin ${{ github.ref_name }} # this could be a different branch to avoid errors
            echo "Successfully pushed $PDF_FILE to the repository."
          fi
